### ISSUE TITLE
Greying of binary image

### ISSUE THREAD

**Issue by aboharbf** [ojwoodford/sc#1]
Hey there,

Great package, thank you so much for writing it. I am attempting to use it to display a set of 0's and 1's previously represented as lines. These lines make the image load very slowly and take a long time. Previously I had looked for help on this in the mathworks forums:

https://www.mathworks.com/matlabcentral/answers/518950-changing-image-rendering?s_tid=prof_contriblnk

your function has made up a great deal of the gap, but the effect sort of remains to a lesser degree. 

![image](https://user-images.githubusercontent.com/25850560/93521349-ede76280-f8fd-11ea-8455-e06986618931.png)

Do you have any advice for how I can tinker with things to make it just black and white, no greys? Thanks a lot for the help.

**Comment by ojwoodford** [comment]
This isn't an issue related to this code, so I'll close this, and respond in MATLAB Answers.

**Comment by aboharbf** [comment]
The reason I posted here is because it seems to some degree to still be due to discretization, which your code improved a lot, but there are still greys where you'd expect only black and white (i.e. its a binary image w/ a non-binary color range for some reason).
